//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryLookup
{
    using System;
    using System.Collections.Generic;
    
    public partial class invlookup
    {
        public int prikey { get; set; }
        public string subcategory { get; set; }
        public Nullable<long> quantity { get; set; }
        public string category { get; set; }
        public string inventory { get; set; }
        public string warehouse { get; set; }
        public string rItem { get; set; }
    }
}
